version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_course
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online_course
      - JWT_SECRET=supersecretkey
      - JWT_REFRESH_SECRET=refreshsupersecretkey
      - JWT_EXPIRES_IN=3600s
      - JWT_REFRESH_EXPIRES_IN=7d
      - PORT=3000
    depends_on:
      - postgres
volumes:
  pgdata: 